app/models.py
from flask_login import UserMixin
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    category = db.Column(db.String)
    post = db.Column(db.String(255))
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comment = db.relationship('Comment',backref='new',lazy='dynamic')


    def save_post(self):
        db.session.add(self)
        db.session.commit()


class User(UserMixin,db.Model):
    __tablename__="users"
    id=db.Column(db.Integer(),primary_key=True)
    username=db.Column(db.String(255),index=True)
    email=db.Column(db.String(255),index=True)
    biography=db.Column(db.String(255))
    profile_pic=db.Column(db.String())
    password_secure=db.Column(db.String(255))
    posts= db.relationship('Post',backref = 'user',lazy ="dynamic")
    comment = db.relationship('Comment',backref='user',lazy='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_secure, password)

    def __repr__(self):
        return f'User: {self.username}'

@login_manager.user_loader
def load_user(user_id):
    """call back function that retrieves a user when a unique identifier is passed"""
    return User.query.get(int(user_id))

def __repr__(self):
    return f'User: {self.name}'



class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'), nullable=False)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, post_id):
        comments_results = Comment.query.filter_by(post_id=post_id).all()

        return comments_results

    def __repr__(self):
        return f'comment:{self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField, SelectField, PasswordField
from wtforms.validators import input_required

categories = ['lifestyle', 'food', 'fashion', 'hobbies']


class UpdateForm(FlaskForm):
    biography = TextAreaField("Your Biography", validators=[input_required(message='Biography field is required')])
    submit = SubmitField("Update Profile")


class PostForm(FlaskForm):
    title = StringField("post title", validators=[input_required(message='post title is required')],
                        render_kw={"placeholder": "post Title"})
    category = SelectField("post category", validators=[input_required(message="post Category required")],
                           choices=categories)
    post = TextAreaField("post description", validators=[input_required(message="post required")],
                         render_kw={"placeholder": "post description"})
    submit = SubmitField("Post post")


class CommentForm(FlaskForm):
    comment = TextAreaField('post comment', validators=[input_required(message="Comment field is required")],
                            render_kw={"placeholder": "Your Comment"})
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES

photos=UploadSet('photos',IMAGES)

mail=Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)


    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from . import main
from flask import render_template, url_for, abort, request, redirect
from flask_login import login_required, current_user
from ..models import User, Post, Comment
from .. import db, photos
from .forms import UpdateForm, PostForm, CommentForm
from ..requests import get_quote


@main.route('/')
def index():
    posts = Post.query.all()
    random_quotes = get_quote()
    return render_template("index.html", posts=posts, quote=random_quotes)


@main.route('/new-post/<id>', methods=['GET', 'POST'])
@login_required
def post(id):
    post_form = PostForm()
    if post_form.validate_on_submit():
        title = post_form.title.data
        category = post_form.category.data
        post = post_form.post.data

        new_post = Post(title=title, category=category, post=post, user=current_user)

        new_post.save_post()
        return redirect(url_for('.showresults'))

    return render_template('post.html', form=post_form)


@main.route('/profile/<my_name>')
@login_required
def profile(my_name):
    title = "Flask Profile"
    user = User.query.filter_by(username=my_name).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user, title=title)


@main.route('/update/<my_name>', methods=['GET', 'POST'])
@login_required
def edit_profile(my_name):
    user = User.query.filter_by(username=my_name).first()
    if user is None:
        abort(404)
    update_form = UpdateForm()
    if update_form.validate_on_submit():
        user.biography = update_form.biography.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile', my_name=user.username))

    return render_template("profile/update.html", update_form=update_form)


@main.route('/updateImage/<my_name>', methods=['POST'])
@login_required
def u_image(my_name):
    user = User.query.filter_by(username=my_name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic = path
        db.session.commit()
    return redirect(url_for('main.profile', my_name=my_name))


@main.route('/comment/<id>', methods=['GET', 'POST'])
@login_required
def comment(id):
    form = CommentForm()
    post = Post.query.get(id)
    fetch_all_comments = Comment.query.filter_by(post_id=id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        post_id = id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment=comment, user_id=user_id, post_id=post_id)
        new_comment.save_comment()
        return redirect(url_for('.comment', id=post_id))
    return render_template('comment.html', comment_form=form, post=post, all_comments=fetch_all_comments)


@main.route('/mychanges')
def showresults():
    responses = Post.query.all()

    return render_template('show.html', all_posts=responses)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    fetches = Post.query.get(id)
    if request.method == 'POST':
        fetches.title = request.form['title']
        fetches.category = request.form['category']
        fetches.post = request.form['post']
        db.session.commit()
        return redirect(url_for(".showresults"))

    return render_template("Modify/update.html", results=fetches)


@main.route('/delete/<id>', methods=["GET", "POST"])
def delete(id):
    data = Post.query.get(id)
    db.session.delete(data)
    db.session.commit()

    return redirect(url_for(".showresults"))

app/templates/Modify/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/Modify/update.html
{%extends 'base.html'%}
{%block content%}
<div class="container mt-4">
    <div class="row">
    <form action="{{url_for('main.edit',id=results.id)}}" method="POST" enctype="multipart/form-data">
      <h1 class="text-info text-center">Update Post</h1>

      <div class="form-group mb-2">
        <label >Post Title</label>
          <input type="text" name="title"  class="form-control" value='{{results.title}}' placeholder="Post Title" required>
      </div>

      <div class="form-group mb-2">
        <label >Post Category</label>

     <select class="form-control" name="category" value='{{results.category}}' id="size">
         <option value="">Select post category</option>
         <option value="lifestyle" {%  if results.category =="lifestyle" %}selected {%endif%}>Lifestyle</option>
         <option value="fashion" {%  if results.category =="fashion" %}selected {%endif%} > Fashion</option>
         <option value="food" {%  if results.category =="food" %}selected {%endif%} >Food</option>
         <option value="hobbies" {%  if results.category =="hobbies" %}selected {%endif%} >Hobbies</option>
     </select>
  </div>
  <div class="form-group mb-2">
    <label>Post Content</label><br>
  <textarea name="post"  class="form-control" >{{results.post}}</textarea>
  </div>

  <div class="form-group mb-2 mt-4">
        <input type="submit" class="btn btn-primary btn-lg" name="update" value="Update Post" required>
    </div>

  </form>

</div>
</div>
{%endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%} {%block styles%} {{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}" />
{%endblock%}

<!-- Navbar block  -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

app/templates/comment.html
{% extends 'base.html'%} {% import 'bootstrap/wtf.html' as wtf %} {% block
    content %}
    <div class="container comments">
      <div class="row">
        {% if all_comments %}
        <div class="col-md-7">
          <h3 class="text"><u>All comments for the post</u></h3>
          {% for comment in all_comments %}
          <div class="card w-90 mb-3">
            <div class="card-body">
                <h5>{{comment.title}}</h5>
                <p class="card-title">{{ comment.comment }}</p>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="col-md-5 commentform">{{wtf.quick_form(comment_form)}}</div>
        </div>
        {%else%}   
        <div class="card w-90 mb-3">
            <div class="card-body">
              <p class="card-title">No Available Comments</p>
            </div>
          </div>
          <div class="col-md-5">{{wtf.quick_form(comment_form)}}</div>
          {%endif%}
        </div>
        
        {% endblock%}         

app/templates/index.html
{%extends 'base.html'%}
{% block content %}
<div class="container-fluid top_image" style="background-image:url({{url_for('static',filename='./images/image.jpg')}})">
<h3 style="color:white" class="text-center"><u> Random Quotes.</u></h3>
    <h2 style="color:white">{{quote.quote}}</h2>
    <p style="color:white">by: {{quote.author}}</p>
</div>
<div class="container">
    <div class="posts">
{%for post in posts%}
<div class="middle">

<h2>{{post.category}}
</h2>
<h3><a href="{{url_for('main.comment',id=post.id)}}">{{post.title}}</a>
</h3>
<p>{{post.post}}</p>
</div>
       {%endfor%}
   
    </div>
    </div>

{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid mt-4">
    <div class="navbar-header">
      <a id="top" class="navbar-brand" href="/">My Personal Blog</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li>
        <a
          style="font-size: 15px; color:white"
          class="btn btn-success"
          href="{{url_for('main.post',id=current_user.id)}}"
          >New Post</a
        >
        <li> <a  href="{{url_for('main.profile',my_name=current_user.username)}}">Profile</a></li>

      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}


      <li><a href="{{url_for('auth.register')}}"> Register</a></li>
      <li><a href="{{url_for('auth.login')}}">Login</a></li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/post.html
{% extends 'base.html'%}
 {% import "bootstrap/wtf.html" as wtf %}

 {% block content %}
 <div class="container">

{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/profile/profile.html
{%extends 'base.html'%} {%block content%}

<div class="container profile">
  <div class="row">
    <div class="col-md-3">
      {%if user.profile_pic%}

      <img
        src="{{url_for('static',filename=user.profile_pic)}}"
        alt=""
        class="img-thumbnail"
      />
      {%else%}
      <h3>No Profile Picture Found</h3>
      {%endif%}
      <h2>{{user.username| capitalize}}</h2>
      {% if user == current_user %}
      <form
        action="{{url_for('main.update_image',my_name=user.username)}}"
        method="post"
        enctype="multipart/form-data"
      >
        <input type="file" name="photo" class="form-control" required />
        <br />
        <input class="btn btn-success" type="submit" />
      </form>
      {% endif %}
    </div>
    <div class="col-md-3">
      {%if user.biography%}
      <p>{{user.biography}}</p>
      {%else%}
      <p>{{user.username}} has no biography yet</p>
      {%endif%} {% if user == current_user %}
      <button class="btn btn-success btn-lg">
        <a
          style="color: white"
          href="{{url_for('main.edit_profile',my_name=user.username)}}"
          >Edit Profile</a
        >
      </button>
      {% endif %}
    </div>
    <div class="col-md-6"></div>
  </div>
</div>

{%endblock%}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block
content %}
<div class="container bio">{{wtf.quick_form(update_form)}}</div>
{% endblock %}

app/templates/show.html
{%extends 'base.html'%} {%block content%}

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<br />
<div class="container-fluid ">
    <div class="row">
        <div class="col-md-12">
  {%for post in all_posts%}
    <div class="card editing">

          <h1>{{post.category}}</h1>
          <h2 >{{post.title}}</h2>
          <h2 >{{post.post}}</h2>

          <div class="row">
                   <button class="btn btn-warning btn-lg"><a style="color:white;font-size:20px" href="{{url_for('main.edit',id=post.id)}}"><i class="fa fa-edit"></i></a></button>
              <button class="btn btn-danger btn-lg"><a style="color:white;font-size:20px" href="{{url_for('main.delete',id=post.id)}}"><i class="fa fa-trash"></i></a></button>

          </div>

    </div>
    {%endfor%}
    </div>
</div>
</div>


{%endblock%}